[workspace]
authors = ["Mr-Leshiy <leshiy12345678@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "onnx-splitter"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025090305,<26"
python = "3.13.*"
numpy = ">=2.3.3,<3"
onnx = ">=1.18.0,<2"

