[project]
name = "python-keras"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = [
    "keras>=3.11.1",
    "onnxruntime>=1.22.1",
    "tensorflow>=2.19.0",
    "tf2onnx>=1.16.1",
]
